### ISSUE TITLE
How to encode/decode an object

### ISSUE THREAD

**Issue by Sparkxxx** [HEADS-project/arduino_msgpck#1]
Hi and thanx for your work

I am looking to encode/decode an array that would look like this
PHP arrays
$data = [ '1234567',
            ['9999999', '7654321', '64'],
                ['62', ['64513451334' => '' ],
                            [
                                'pin1'=>['5,2,4'],
                                'ipin2'=>[5,2,'readIC'=>3],
                                4=>[2=>80]
                            ]  
                ] 
          ];

I looked at the examples but I can not understand how can I use it for such arrays which are more real life and would like to pack everything and send it in 1 package rather than splitting it in multiple parts like the examples show.

Thank you.

**Comment by nharrand** [comment]
As message pack is derivated from json, I think you'll need to tweak a little bit your array.
(On [json Website](http://json.org/) you can find about json's grammar if that's a problem.)

But basically, your message need to be a map of objects "key":value, where key is a string, and value can be pretty much anything.
So if your message is just an array you can encode it as a map of 1 object.
Furthermore, you won't be able to have things like 1=>5, but you may have "1"=>5 if you want.

So if you want to send an array [1,2,3] you will have to send {"msgID":[1,2,3]}

```
// Map with 1 object
msgpck_write_map_header(&s, 1); //{
msgpck_write_string(&s, "msgID"); // "msgID"
//:
msgpck_write_array_header(&s, 3); //[
msgpck_write_integer(&s, 1); //1,
msgpck_write_integer(&s, 2); //2,
msgpck_write_integer(&s, 3); //3
//]
//}
```

If you want to have an array nested in another like{"msgID":[1,2,["mystring", nil, 123, 5]]}

```
// Map with 1 object
msgpck_write_map_header(&s, 1); //{
msgpck_write_string(&s, "msgID"); // "msgID"
//:
msgpck_write_array_header(&s, 3); //[
msgpck_write_integer(&s, 1); //1,
msgpck_write_integer(&s, 2); //2,

msgpck_write_array_header(&s, 4); //[
msgpck_write_string(&s, "mystring"); // "mystring",
msgpck_write_map_nil(); // nil,
msgpck_write_integer(&s, 123); //123,
msgpck_write_integer(&s, 5); //5
//]
//]
//}
```

If you have objects such as {"msgID":[1,2,{"pin1" : 20}} in your array you need to express them as map of 1 object

```
// Map with 1 object
msgpck_write_map_header(&s, 1); //{
msgpck_write_string(&s, "msgID"); // "msgID"
//:
msgpck_write_array_header(&s, 3); //[
msgpck_write_integer(&s, 1); //1,
msgpck_write_integer(&s, 2); //2,
msgpck_write_map_header(&s, 1); //{
msgpck_write_string(&s, "pin1"); // "pin1"
//:
msgpck_write_integer(&s, 20); //20
//}
//]
//}
```

Decoding on the arduino side is more tricky if you don't know in advance what your message will look like, but  you can use the function `msgpck_what_next(Stream * s);` in order to read on the go the next type you'll be reading and switch acording to the result to the appropriate `msgpck_read`.

I hope it answers your question.
